### ISSUE TITLE
[Suggestion] Bug & 小小的细节

### ISSUE THREAD

**Issue by zhaobozhen** [Libv-Team/MiaD-Suggestion#31]
VersionCode 380

- 主页 云备份 ToolTip 错误显示为 “内容检索”
- 在进入编辑器页面后退出再进入关于页 Toolbar 会显示 menu
- 划出抽屉后返回会直接退出应用
- 未登录情况下点击主页 云备份 按钮总是会弹出 "加载中"
- 深色模式下 预览页面字体貌似是黑色？

**Comment by JalorOo** [comment]
已修复完成
